### ISSUE TITLE
Change the "Not a valid number" message in "kaga"

### ISSUE THREAD

**Issue by Tetriser** [NostalgiaNinja/Puyobot#15]
Since the `kaga` command now has 20 images, maybe you want to change the message?
```
Not a valid number!  Specify a number from 0 to 19 to receive your sleep message!
```

**Comment by NostalgiaNinja** [comment]
Changed in production.  Will make a change in github promptly.

Thanks

**Comment by NostalgiaNinja** [comment]
Fixed through github.  Will close the issue.
